/*
 * rotary_encoder.config.h
 *
 *  Created on: Jun 9, 2022
 *      Author: yurib
 */

#ifndef INC_LIB_ROTARY_ENCODER_CONFIG_H_
#define INC_LIB_ROTARY_ENCODER_CONFIG_H_
#include "main.h"

#define ROTARY_ENCODER_TIM_CLOCK LL_APB1_GRP1_PERIPH_TIM4
#define ROTARY_ENCODER_GPIO_CLOCK LL_AHB1_GRP1_PERIPH_GPIOB
#define ROTARY_ENCODER_TIM_CHANNEL1 LL_GPIO_PIN_6
#define ROTARY_ENCODER_TIM_CHANNEL2 LL_GPIO_PIN_7
#define ROTARY_ENCODER_TIM_IRQ TIM4_IRQn
#define ROTARY_ENCODER_PRIORITYGROUPING NVIC_EncodePriority(NVIC_GetPriorityGrouping(),5, 0)
#define ROTARY_ENCODER_TIMER TIM4


#endif /* INC_LIB_ROTARY_ENCODER_CONFIG_H_ */
